version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - cd C:\Users\prash\Desktop\pp\git\personal\my\AWS-lambda
      - mvn clean install

  post_build:
    commands:
      - aws lambda update-function-code --function-name lambda-deploye --zip-file fileb://target/YourProjectName-1.0-SNAPSHOT.jar
